### ISSUE TITLE
Can't login from the login screen

### ISSUE THREAD

**Issue by NhatTienmode** [nganngants/QLTV#76]
I am experiencing a problem when trying to connect to the database during the login process. The error indicates that it cannot find the database to retrieve the user credentials, even though the database appears to be present and shows the full tables and data:
![image](https://github.com/nganngants/QLTV/assets/151420046/a2c6fc00-aeb6-49ec-81fb-8c64784d848b)

I have ensured that all the required extensions are installed:
.NET Framework 4.7.2
Entity Framework 6.4.4
SQL Server
Siticone UI/UX Framework

Additionally, I have installed all the required NuGet packages, including Entity Framework 6.4.4 and Siticone UI/UX Framework.

**Comment by nganngants** [comment]
Hi. Please make sure you have added connection to the database, check in View -> Server Explorer. Also, check the connection string in `DAL/App.config`, I set it to use local as data source but there may be some conflict in different machines.

**Comment by NhatTienmode** [comment]
Do I need to install any extra programs (exe, msi files) or dependencies for the code to run, as the two causes you mentioned above seem fine:
![image](https://github.com/nganngants/QLTV/assets/151420046/ad02e53e-d7ff-47f2-b6f0-532aa6576473)

**Comment by nganngants** [comment]
> Do I need to install any extra programs (exe, msi files) or dependencies for the code to run, as the two causes you mentioned above seem fine: ![image](https://private-user-images.githubusercontent.com/151420046/333524140-ad02e53e-d7ff-47f2-b6f0-532aa6576473.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTE0NjEsIm5iZiI6MTcxNjU1MTE2MSwicGF0aCI6Ii8xNTE0MjAwNDYvMzMzNTI0MTQwLWFkMDJlNTNlLWQ3ZmYtNDdmMi1iNmYwLTUzMmFhNjU3NjQ3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMTQ2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2IzODQxYmFmM2I5NDFlZGI5N2I2MzY4YmQ4NzJkZjBhYjdkYzA5YjgyMWI3NzI2NTEyY2ExYzIzNTMwMTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gUPIrZPdlKnNZk26oMzxeC0_Vwi12ybSDwNVToHbGQk)

It looks like you have not added the connection yet. In the server explorer, right click on Data Connections and add the database you use for this app.

**Comment by NhatTienmode** [comment]
![image](https://github.com/nganngants/QLTV/assets/151420046/cd3ab471-b614-48bc-bd24-217df2cf2d3e)

Are these options correct? I tried them out, but I can't find my server (which I suppose was TheBeast). When I tried to type it in manually, it didn't find the database name.

![image](https://github.com/nganngants/QLTV/assets/151420046/8376f0ca-3e3e-47ad-a18d-64a9e021bae1)

**Comment by nganngants** [comment]
Yes the options are correct. You can try clicking Test Connection after filling out the server name, if the name is correct, there should be a successful message. Otherwise, you can find the solution online.  I’m not quite familiar with this though

**Comment by NhatTienmode** [comment]
I solved it using this [guide](https://stackoverflow.com/a/38641107) by enabling and changing the TCP port and an restart the SQL service. Thanks anyway.
